-- Importación manual de demostración. Todo queda OCULTO hasta revisión.
begin;
do $import$
begin
if exists(select 1 from private.catalog_imports where name = 'demo-v1') then raise notice 'La demostración ya se importó'; return; end if;
insert into public.categories(name, slug, description, image_path, active, sort_order) values ('Muñecos navideños', 'munecos-navidenos', 'Personajes entrañables, puntada a puntada, para acompañar tus tradiciones.', '/images/placeholders/santa.svg', false, 1) on conflict (slug) do nothing;
insert into public.categories(name, slug, description, image_path, active, sort_order) values ('Adornos para el árbol', 'adornos-para-el-arbol', 'Pequeños detalles que hacen único el rincón más especial de la Navidad.', '/images/placeholders/angel.svg', false, 2) on conflict (slug) do nothing;
insert into public.categories(name, slug, description, image_path, active, sort_order) values ('Coronas', 'coronas', 'Una bienvenida hecha a mano para compartir la alegría de volver a casa.', '/images/placeholders/wreath.svg', false, 3) on conflict (slug) do nothing;
insert into public.categories(name, slug, description, image_path, active, sort_order) values ('Centros de mesa', 'centros-de-mesa', 'Creaciones para reunir a quienes quieres alrededor de una mesa especial.', '/images/placeholders/table.svg', false, 4) on conflict (slug) do nothing;
insert into public.categories(name, slug, description, image_path, active, sort_order) values ('Decoración para el hogar', 'decoracion-para-el-hogar', 'Estamos preparando nuevos detalles para llevar la Navidad a cada rincón.', '/images/placeholders/stocking.svg', false, 5) on conflict (slug) do nothing;
insert into public.products(category_id, name, slug, short_description, description, price, price_from, availability, production_time, customizable, customization_options, featured, active, sort_order, images) values ((select id from public.categories where slug = 'munecos-navidenos'), 'Papá Noel de Navidad', 'papa-noel-de-navidad', 'Un personaje lleno de ternura y tradición.', 'Papá Noel decorativo en tela, con gorro rojo y detalles cosidos a mano. Una pieza para acompañar el árbol, decorar una repisa o convertirse en un regalo especial. El acabado y las medidas se acuerdan al realizar el pedido.', 85000, true, 'made_to_order', 'De 7 a 10 días hábiles', true, array['Nombre bordado','Tamaño a convenir','Detalles de la vestimenta' ]::text[], true, false, 1, '[{"kind":"placeholder","alt":"Ilustración de demostración: Papá Noel de tela en rojo y blanco","width":600,"height":720,"path":"/images/placeholders/santa.svg"},{"kind":"placeholder","alt":"Ilustración de demostración: detalle ilustrado del gorro y las puntadas de Papá Noel","width":600,"height":720,"path":"/images/placeholders/santa-detail.svg"}]'::jsonb) on conflict (slug) do nothing;
insert into public.products(category_id, name, slug, short_description, description, price, price_from, availability, production_time, customizable, customization_options, featured, active, sort_order, images) values ((select id from public.categories where slug = 'coronas'), 'Corona Dulce Bienvenida', 'corona-dulce-bienvenida', 'La magia comienza desde la puerta.', 'Corona decorativa con piezas textiles, lazo rojo y pequeños detalles artesanales. Pensada para puertas interiores o espacios protegidos. Podemos conversar sobre el tamaño y los detalles que mejor acompañan tu hogar.', 120000, true, 'made_to_order', 'De 8 a 12 días hábiles', true, array['Inicial de la familia','Diámetro a convenir','Mensaje de bienvenida' ]::text[], true, false, 2, '[{"kind":"placeholder","alt":"Ilustración de demostración: corona roja con lazo y detalles blancos","width":600,"height":720,"path":"/images/placeholders/wreath.svg"}]'::jsonb) on conflict (slug) do nothing;
insert into public.products(category_id, name, slug, short_description, description, price, price_from, availability, production_time, customizable, customization_options, featured, active, sort_order, images) values ((select id from public.categories where slug = 'adornos-para-el-arbol'), 'Angelito de los Deseos', 'angelito-de-los-deseos', 'Un pequeño deseo en cada rama.', 'Ángel de tela para colgar en el árbol o acompañar un regalo. Sus alas blancas y su vestido rojo evocan la sencillez de una Navidad en familia. Cada detalle se termina a mano, por lo que las piezas pueden presentar pequeñas variaciones.', 28000, false, 'available', 'Consultar tiempo de entrega', true, array['Inicial bordada','Presentación para regalo' ]::text[], true, false, 3, '[{"kind":"placeholder","alt":"Ilustración de demostración: ángel artesanal con alas blancas y vestido rojo","width":600,"height":720,"path":"/images/placeholders/angel.svg"}]'::jsonb) on conflict (slug) do nothing;
insert into public.products(category_id, name, slug, short_description, description, price, price_from, availability, production_time, customizable, customization_options, featured, active, sort_order, images) values ((select id from public.categories where slug = 'centros-de-mesa'), 'Centro de mesa Nochebuena', 'centro-de-mesa-nochebuena', 'Un detalle para compartir y celebrar.', 'Composición decorativa con flores textiles y velas ornamentales, ideal para una mesa navideña. Las velas de esta propuesta son decorativas y no deben encenderse. El diseño final se acuerda según el espacio disponible.', 95000, true, 'made_to_order', 'De 7 a 10 días hábiles', true, array['Largo de la composición','Cantidad de flores textiles' ]::text[], true, false, 4, '[{"kind":"placeholder","alt":"Ilustración de demostración: centro de mesa rojo y blanco con velas ornamentales","width":600,"height":720,"path":"/images/placeholders/table.svg"}]'::jsonb) on conflict (slug) do nothing;
insert into public.products(category_id, name, slug, short_description, description, price, price_from, availability, production_time, customizable, customization_options, featured, active, sort_order, images) values ((select id from public.categories where slug = 'adornos-para-el-arbol'), 'Estrella de los Sueños', 'estrella-de-los-suenos', 'Puntadas que guardan buenos deseos.', 'Estrella acolchada de tela roja, terminada con puntadas visibles y una cinta para colgar. Un detalle ligero para decorar el árbol o personalizar los regalos de la familia.', 18000, false, 'made_to_order', 'De 4 a 6 días hábiles', true, array['Inicial bordada','Tamaño a convenir' ]::text[], false, false, 5, '[{"kind":"placeholder","alt":"Ilustración de demostración: estrella acolchada roja con costuras blancas","width":600,"height":720,"path":"/images/placeholders/star.svg"}]'::jsonb) on conflict (slug) do nothing;
insert into public.products(category_id, name, slug, short_description, description, price, price_from, availability, production_time, customizable, customization_options, featured, active, sort_order, images) values ((select id from public.categories where slug = 'munecos-navidenos'), 'Gnomo Copito', 'gnomo-copito', 'Un compañero para tus rincones favoritos.', 'Gnomo decorativo con gorro alto y barba blanca, elaborado en tela. Esta propuesta no está disponible en este momento; puedes consultarnos por alternativas o por una futura elaboración.', 65000, false, 'sold_out', 'Por confirmar al retomar su elaboración', true, array['Tamaño a convenir' ]::text[], false, false, 6, '[{"kind":"placeholder","alt":"Ilustración de demostración: gnomo de tela con gorro rojo y barba blanca","width":600,"height":720,"path":"/images/placeholders/gnome.svg"}]'::jsonb) on conflict (slug) do nothing;
insert into private.catalog_imports(name) values ('demo-v1');
end;
$import$;
commit;
